[web]
wiki-web ansible_host=10.0.1.16

[db]
wiki-db ansible_host=10.0.1.17

[all:vars]
ansible_user=devops
ansible_ssh_private_key_file=~/.ssh/wiki_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=root@82.64.141.52:4007'
