---
- name: Configurer la base de donnees
  hosts: db
  become: true
  roles:
    - common
    - postgresql

- name: Configurer le serveur web
  hosts: web
  become: true
  roles:
    - common
    - wikijs
    - nginx
